# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"k\n\x08testinfo\x12\x0f\n\x07\x64\x65vtype\x18\x01 \x01(\x05\x12\r\n\x05\x64\x65vid\x18\x02 \x01(\x05\x12\x0e\n\x06unitid\x18\x03 \x01(\x05\x12\r\n\x05\x63hlid\x18\x04 \x01(\x05\x12\x0e\n\x06testid\x18\x05 \x01(\x05\x12\x10\n\x08stepdata\x18\x06 \x01(\x0c\x62\x06proto3')



_TESTINFO = DESCRIPTOR.message_types_by_name['testinfo']
testinfo = _reflection.GeneratedProtocolMessageType('testinfo', (_message.Message,), {
  'DESCRIPTOR' : _TESTINFO,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:testinfo)
  })
_sym_db.RegisterMessage(testinfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTINFO._serialized_start=14
  _TESTINFO._serialized_end=121
# @@protoc_insertion_point(module_scope)
