# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DanmuGameProtocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44\x61nmuGameProtocol.proto\x12\x11\x44\x61nmuGameProtocol\"S\n\x08MainPack\x12\x13\n\x0bMessageType\x18\x01 \x01(\r\x12\x0e\n\x06UserID\x18\x02 \x01(\x05\x12\x10\n\x08UserName\x18\x03 \x01(\t\x12\x10\n\x08UserText\x18\x04 \x01(\t*>\n\x0bMessageType\x12\x0b\n\x07\x64\x61nmaku\x10\x00\x12\x08\n\x04gift\x10\x01\x12\t\n\x05guard\x10\x02\x12\r\n\tsuperchat\x10\x03\x62\x06proto3')

_MESSAGETYPE = DESCRIPTOR.enum_types_by_name['MessageType']
MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
danmaku = 0
gift = 1
guard = 2
superchat = 3


_MAINPACK = DESCRIPTOR.message_types_by_name['MainPack']
MainPack = _reflection.GeneratedProtocolMessageType('MainPack', (_message.Message,), {
  'DESCRIPTOR' : _MAINPACK,
  '__module__' : 'DanmuGameProtocol_pb2'
  # @@protoc_insertion_point(class_scope:DanmuGameProtocol.MainPack)
  })
_sym_db.RegisterMessage(MainPack)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGETYPE._serialized_start=131
  _MESSAGETYPE._serialized_end=193
  _MAINPACK._serialized_start=46
  _MAINPACK._serialized_end=129
# @@protoc_insertion_point(module_scope)
