# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"F\n\x08MainPack\x12\x10\n\x08UserName\x18\x01 \x01(\t\x12\x10\n\x08UserText\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\x62\x06proto3')



_MAINPACK = DESCRIPTOR.message_types_by_name['MainPack']
MainPack = _reflection.GeneratedProtocolMessageType('MainPack', (_message.Message,), {
  'DESCRIPTOR' : _MAINPACK,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.MainPack)
  })
_sym_db.RegisterMessage(MainPack)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAINPACK._serialized_start=20
  _MAINPACK._serialized_end=90
# @@protoc_insertion_point(module_scope)
